### ISSUE TITLE
pip install failing 

### ISSUE THREAD

**Issue by arunpatro** [mgui7/diagonal-LA-for-object-detection#2]
Hey, this is failing to install! Can you please help?

```
(bml) user123@abcdedf:~/nyu/diagonal-LA-for-object-detection$ pip install -r requirements.txt
Collecting matplotlib==2.1.1 (from -r requirements.txt (line 1))
  Using cached matplotlib-2.1.1.tar.gz (36.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /tmp/pip-install-g7sgs0h3/matplotlib_adb0495b8cb8447c8124f09b558061f0/setupext.py:2223: SyntaxWarning: invalid escape sequence '\.'
        pattern = '(3\.1\d+)|(MiKTeX \d+.\d+)'
      /tmp/pip-install-g7sgs0h3/matplotlib_adb0495b8cb8447c8124f09b558061f0/versioneer.py:472: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-g7sgs0h3/matplotlib_adb0495b8cb8447c8124f09b558061f0/setup.py", line 58, in <module>
          __version__ = versioneer.get_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-g7sgs0h3/matplotlib_adb0495b8cb8447c8124f09b558061f0/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-g7sgs0h3/matplotlib_adb0495b8cb8447c8124f09b558061f0/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-g7sgs0h3/matplotlib_adb0495b8cb8447c8124f09b558061f0/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by arunpatro** [comment]
I was using python3.12, now using python3.9 solves this issue.
